# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ispt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('tipo_tabla', models.CharField(blank=True, max_length=4, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cuota_fija', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('excedente', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('bruto', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabulador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('zona_economica', models.IntegerField(blank=True, default=2, null=True)),
                ('nivel', models.CharField(blank=True, max_length=4, null=True)),
                ('rango', models.IntegerField(blank=True, default=0, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('compensacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
        ),
    ]
